### ISSUE TITLE
Dynamic options list in Editable select column

### ISSUE THREAD

**Issue by yakirg** [AllenFang/react-bootstrap-table#1423]
I have a problem where I have one column that is a type and another that is a refine on said type:
```
const posTypes = ["Any", "Noun", "Verb", "Adjective", "Adverb", "Cardinal number"];
const posRefineTypes = {
  "Any": [],
  "Noun": ["Any", "Single", "Plural", "Proper noun single", "Proper noun plural"],
  "Verb": ["Any", "Base form", "Past tense", "gerund or present participle", "past participle", "non-3rd person singular present", "3rd person singular present"],
  "Adjective": ["Any", "Comparative", "Superlative"],
  "Adverb": ["Any", "Comparative", "Superlative"],
  "Cardinal number": []
};
...

           <TableHeaderColumn
                dataField='Pos' editable={ {type: 'select', options: {values: posTypes}} }
                width={"120px"}>
              Pos
            </TableHeaderColumn>

            <TableHeaderColumn
                dataField='Refine'
                editable={  {type: 'select', options: {values: posRefineTypes[Pos]}} }
                width={"120px"}>
              Refine
            </TableHeaderColumn>   

```

I need the options in the sub type to match the type, but it has to be a constant.

Is there a way to get it done?

**Comment by yakirg** [comment]
Pos is one column select value (stands for Parts Of Speech)
Refine is the next column, which has options that relate to the value selected in Pos.

Hope this clears a bit ...

**Comment by AllenFang** [comment]
@yakirg, I probably know your requirement, I'll consider to add this feature by a callback function, you can decide what options list you want depend on row data, that's what I think but I need to check code and no schedule promise here, sorry for that due to busy recently. thanks

**Comment by yakirg** [comment]
@Allen, a callback will be great!  Thanks.

**Comment by yakirg** [comment]
Created a PR with a suggested fix.
It is still problematic on the insert new dialog part, because the row doesn't exist, but it's usable as is.

**Comment by AllenFang** [comment]
@yakirg, nice !! I will check this out. 👍

**Comment by AllenFang** [comment]
Fixed on `v4.0.0-beta.8`

**Comment by AllenFang** [comment]
`v4.0.0` release

**Comment by ForumT** [comment]
Hi can you give an example of how to implement this? I need a similar functionality

**Comment by shanben7** [comment]
Hi, I believe I am still having the problem @yakirg mentioned where the the "row" is undefined in the insert dialog, and so I cannot choose my values this way for the insert dialog. Is there a fix for this?

**Comment by yakirg** [comment]
The insert dialog was never fixed, and I had difficulty implementing it, as
there is no 'row' object available at that stage. I wish it was fixed, but
it was not critical for my application, so I did not pursue it further.

**Comment by nkarmak** [comment]
I am not able to get this going. I am trying to filter the drop down menu options based on the value of one of the other columns, but the column it depends on is not editable. 
```
    const dropDownOptions = {
      type: 'select',
      options: { values: this.state.selected_values['Product_Name'] }
    };
```
this.state.selected_values is an object which has the same structure as posRefineTypes defined above, with the key being values of 'Product_Name' and the values being array of facilities. 

      <TableHeaderColumn width='35%' dataField='Product_Name' isKey dataAlign="center" dataSort={ true } >Product Name</TableHeaderColumn>
      <TableHeaderColumn width='35%' dataField='facility_name'  dataAlign="center" editable={dropDownOptions} dataSort={ true }>Fixed Facillity Name</TableHeaderColumn>

```
Is this correct?

**Comment by ashish00076** [comment]
@AllenFang @yakirg was the insert dialog issue fixed here ?

Please respond, critical situation.

Thanks & Regards,
Ashish Deshpande

**Comment by yakirg** [comment]
My last comment still stands. The insert was never fixed (to my knowledge) but it's not too critical for me, my users create first and edit later.

**Comment by NikhithaPeesari** [comment]
> I am not able to get this going. I am trying to filter the drop down menu options based on the value of one of the other columns, but the column it depends on is not editable.
> 
> ```
>     const dropDownOptions = {
>       type: 'select',
>       options: { values: this.state.selected_values['Product_Name'] }
>     };
> ```
> 
> this.state.selected_values is an object which has the same structure as posRefineTypes defined above, with the key being values of 'Product_Name' and the values being array of facilities.
> 
> ```
>   <TableHeaderColumn width='35%' dataField='Product_Name' isKey dataAlign="center" dataSort={ true } >Product Name</TableHeaderColumn>
>   <TableHeaderColumn width='35%' dataField='facility_name'  dataAlign="center" editable={dropDownOptions} dataSort={ true }>Fixed Facillity Name</TableHeaderColumn>
> ```
> 
> ```
> Is this correct?
> ```

i am facing a similar issue. Any suggestions on how to resolve it?Thanks.
