### ISSUE TITLE
BUG: invariant.js:38 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded 

### ISSUE THREAD

**Issue by rasmuslundberg** [AllenFang/react-bootstrap-table#863]
Im getting this error message, 

```
invariant.js:38 Uncaught (in promise) Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded 
```
react-bootstrap-table has worked perfectly until all of a sudden this appeared. I have tried to alias. Im using:
"react-bootstrap-table": "^2.6.0",

Also using webpack, tried: 
  resolve: {
    alias: {
      'react': path.resolve(__dirname, '../node_modules/react')
    },
    extensions: ['', '.js', 'jsx']
  },
..But that didn't help. 

Based on the error message there is some refs misson on ComponentDidUnMount() when a new table is requested... Anyone have a idea whats wrong?

**Comment by rasmuslundberg** [comment]
An update, the subpackage react-toastr has another version of react than i use, this causes a crash that makes my app unusable... How can i prevent this?

**Comment by AllenFang** [comment]
Check #838 and [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L70) 

Cause of ```react-toastr``` have some issue on ```react@15.4.x```, so I fork it and restricts its react version as less than ```15.4.x```.  it's a workaround for now. BTW what's the version of react and when did you got this error message?

**Comment by musbaig** [comment]
Hello: I'm seeing this error also. Interestingly enough it only showed up after we deployed our code to AWS, thus, adding some real testable latency to everything. Not seeing the issue locally, which is odd. Btw, I have `react-toastr` v2.8.2 installed as well.

**Comment by musbaig** [comment]
Update: so I removed `react-toastr` entirely from my app, since I didn't need it just yet, and redeployed, but, still seeing the same error, which is making the app unusable.

**Comment by musbaig** [comment]
Update 2: @rasmuslundberg rolling back to v2.5.9 will resolve the issue for now.

**Comment by AllenFang** [comment]
@musbaig, what's the version of your ```npm```. I'm also Interesting that you still encounter the error after uninstall ```reat-toastr```. 

In you local development, did you remove the ```node_module``` dir and install all again?

**Comment by rasmuslundberg** [comment]
Hi!

@AllenFang im running react 15.4.0, i got this message in out prod and test environments but not locally. Just as you @musbaig... i rolled back immidiatelly. Thank you for the Quick response!

**Comment by AllenFang** [comment]
@rasmuslundberg, what's the npm version you used? And because I test it on my local, it's all fine. Currently, there's only one known bug is that if you use ```npm@2``` and ```react@0.14.x``` will throw some error messages when webpacking, see https://github.com/AllenFang/react-bootstrap-table/issues/838#issuecomment-263470839

BTW, if you can, please tell the your npm version, react version, your step to reproduce and which step got the error is better to me to find the root cause. If a simple and minimal repo for me is awesome.

Thanks :)

**Comment by musbaig** [comment]
@AllenFang I'm running `npm@3.10.9` and `react@15.4.1` in my aws deploy. Not much I can add in terms of reproducibility, I have a basic table, starts with empty data array that is later populated with real data via api call, that's it really. Table is basic, no components embedded in any of the cells. Incidentally, locally I'm using `npm @3.10.3` and `react@15.4.1`.

**Comment by AllenFang** [comment]
@musbaig, thanks, I'll check this out :)

**Comment by AllenFang** [comment]
hi all, I've test on my local with ```react@15.4.1``` and ```react-bootstrap-table@2.6.0``` but I have no any error on webpacking or running. BTW, ```npm@3.3.2``` and ```node@6.0.0```

BTW, I just setup a simple react boilerplate and change react version as ```^15.0.0``` and add ```react-bootstrap-table```, finally run ```npm install```, 
after installation, there's no any peerdependency are missing and everything is fine.

In ```v2.6.0```, as I mentioned before, I fork ```react-toastr``` and make its ```react``` version less than ```15.4.x```. So in my consideration, if you use npm@3 and have a react@15.4.1 env, after you installing ```react-bootstrap-table```, you will see the ```react-toastr``` be installed it self react version with ```15.3.2```, as following:

![Imgur](http://i.imgur.com/YGJ4946.png)

**Comment by MeloDai** [comment]
"<script src="build/react.js"></script>
	    <script src="build/react-with-addons.js"></script>
	    <script src="build/react-dom.min.js"></script>
	    <script src="build/react-dom-server.js"></script>" this will work

"	    <script src="build/react.js"></script>
	    <script src="build/react-dom.min.js"></script>
	    <script src="build/react-dom-server.js"></script>
	    <script src="build/react-with-addons.js"></script>" this will cause bug

**Comment by gauravagam** [comment]
Hey @AllenFang  I am facing the same issue. I am using node@5.3.0, npm@4.1.2, react@15.4.2 and react-bootstrap-table@2.11.2.  Please reply me as soon as possible. Here is the screenshop of table installation 
![react-bootstrap-table-install](https://cloud.githubusercontent.com/assets/13509083/22773607/0b3201ee-eec9-11e6-9fc2-77358fa54513.jpg)

**Comment by AllenFang** [comment]
@gauravagam, sorry, this issue is supposed to be fixed, but I still cant reproduce this issue currently,  I will try again with your environment.

**Comment by gauravagam** [comment]
Ok @AllenFang

**Comment by Kitanotori** [comment]
I'm getting this issue after cloning react-bootstrap-table locally, building it, and `npm install`ing it from the cloned directory.

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216

**Comment by AllenFang** [comment]
After `v4.0.0`, `react-bootstrap-table doesn't use `react-toastr` anymore.
